@counterAPI_HostAddress = https://localhost:7027

GET {{counterAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{counterAPI_HostAddress}}/api/counters
Content-Type: application/json
{
  "id":"1",
  "value":"42",
  "name":"a"
}

###
